# Generated by Django 6.0.4 on 2026-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('function', models.CharField(choices=[('iGV', 'iGV'), ('oGV', 'oGV'), ('iGTa', 'iGTa'), ('oGTa', 'oGTa'), ('iGTe', 'iGTe'), ('oGTe', 'oGTe'), ('MKT', 'MKT'), ('FIN', 'FIN'), ('TM', 'TM'), ('BD', 'BD'), ('PM', 'PM'), ('OTHER', 'OTHER'), ('ALL', 'ALL')], default='ALL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], default='MCQ', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('function', models.CharField(choices=[('iGV', 'iGV'), ('oGV', 'oGV'), ('iGTa', 'iGTa'), ('oGTa', 'oGTa'), ('iGTe', 'iGTe'), ('oGTe', 'oGTe'), ('MKT', 'MKT'), ('FIN', 'FIN'), ('TM', 'TM'), ('BD', 'BD'), ('PM', 'PM'), ('OTHER', 'OTHER'), ('ALL', 'ALL')], default='ALL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('passing_score', models.FloatField(default=70.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
